FROM oven/bun:1.4.2

WORKDIR /app

COPY package.json bun.lock turbo.json tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
COPY drizzle ./drizzle

RUN bun install --frozen-lockfile

ENV NODE_ENV=production

CMD ["bun", "apps/api/src/server.ts"]
