import { describe, expect, it } from "vitest";
import { shapeYoutubeTranscriptSearchOutput } from "@/lib/capabilities/youtube-transcript-search";

describe("shapeYoutubeTranscriptSearchOutput", () => {
  it("returns bounded timestamped context around a transcript phrase", () => {
    const result = shapeYoutubeTranscriptSearchOutput(
      [
        {
          video_id: "video123456",
          title: "A sponsored video",
          channel_name: "Example Channel",
          language: "en",
          selected_language: "English",
          is_auto_generated: true,
          duration_seconds: 120,
          available_languages: ["English", "German"],
          status: "success",
          transcript: [
            { start: 0, end: 10, text: "Welcome back to the channel." },
            { start: 10, end: 20, text: "Today's video is brought to you by" },
            {
              start: 20,
              end: 30,
              text: "WorkOS, the authentication platform.",
            },
            {
              start: 30,
              end: 40,
              text: "Thanks to WorkOS for sponsoring this video.",
            },
            { start: 90, end: 100, text: "Now back to the main topic." },
          ],
        },
      ],
      {
        videoUrl: "https://www.youtube.com/watch?v=video123456",
        query: "workos",
        contextSeconds: 15,
        maxMatches: 3,
      },
    );

    expect(result).toMatchObject({
      video: {
        id: "video123456",
        title: "A sponsored video",
        channel: "Example Channel",
        url: "https://www.youtube.com/watch?v=video123456",
        language: "en",
        selectedLanguage: "English",
        isAutoGenerated: true,
        durationSeconds: 120,
      },
      query: "workos",
      searchedSegmentCount: 5,
      matchedSegmentCount: 2,
      availableLanguages: ["English", "German"],
      matches: [
        {
          startSeconds: 0,
          endSeconds: 40,
          startTime: "00:00:00",
          endTime: "00:00:40",
          url: "https://www.youtube.com/watch?v=video123456&t=0s",
        },
      ],
    });
    expect(result.matches[0]?.text).toContain("WorkOS, the authentication platform.");
    expect(result.matches[0]?.text).toContain("Thanks to WorkOS for sponsoring");
  });

  it("matches a phrase split across adjacent transcript segments", () => {
    const result = shapeYoutubeTranscriptSearchOutput(
      [
        {
          video_id: "video123456",
          status: "success",
          transcript: [
            { start: 100, end: 102, text: "Thank you to Work" },
            { start: 102, end: 106, text: "OS for sponsoring this video." },
          ],
        },
      ],
      {
        videoUrl: "https://www.youtube.com/watch?v=video123456",
        query: "work os",
        contextSeconds: 15,
        maxMatches: 1,
      },
    );

    expect(result.matchedSegmentCount).toBe(1);
    expect(result.matches).toHaveLength(1);
    expect(result.matches[0]?.text).toContain("Thank you to Work OS for sponsoring");
  });

  it("returns a useful empty result instead of unrelated transcript text", () => {
    const result = shapeYoutubeTranscriptSearchOutput(
      [
        {
          video_id: "video123456",
          status: "success",
          transcript: [{ start: 0, end: 5, text: "An unrelated introduction." }],
        },
      ],
      {
        videoUrl: "https://www.youtube.com/watch?v=video123456",
        query: "workos",
        contextSeconds: 60,
        maxMatches: 3,
      },
    );

    expect(result.matchedSegmentCount).toBe(0);
    expect(result.matches).toEqual([]);
    expect(result.note).toMatch(/spelling variant/i);
  });

  it("keeps the matching segment when a context window exceeds the excerpt cap", () => {
    const result = shapeYoutubeTranscriptSearchOutput(
      [
        {
          video_id: "video123456",
          status: "success",
          transcript: [
            { start: 0, end: 30, text: "before ".repeat(400) },
            { start: 30, end: 35, text: "WorkOS sponsor read" },
            { start: 35, end: 65, text: "after ".repeat(400) },
          ],
        },
      ],
      {
        videoUrl: "https://www.youtube.com/watch?v=video123456",
        query: "workos",
        contextSeconds: 60,
        maxMatches: 1,
      },
    );

    expect(result.matches[0]?.text.length).toBeLessThanOrEqual(3_600);
    expect(result.matches[0]?.text).toContain("WorkOS sponsor read");
  });

  it("omits absent optional metadata instead of serializing undefined values", () => {
    const result = shapeYoutubeTranscriptSearchOutput(
      [
        {
          video_id: "video123456",
          status: "success",
          transcript: [{ start: 0, end: 5, text: "A WorkOS mention." }],
        },
      ],
      {
        videoUrl: "https://www.youtube.com/watch?v=video123456",
        query: "workos",
        contextSeconds: 15,
        maxMatches: 1,
      },
    );

    expect(result.video).toEqual({
      id: "video123456",
      url: "https://www.youtube.com/watch?v=video123456",
    });
    expect(result).not.toHaveProperty("availableLanguages");
  });

  it("rejects failed or malformed provider output", () => {
    expect(() =>
      shapeYoutubeTranscriptSearchOutput(
        [
          {
            video_id: "video123456",
            status: "error",
            message: "untrusted provider detail",
          },
        ],
        {
          videoUrl: "https://www.youtube.com/watch?v=video123456",
          query: "workos",
          contextSeconds: 60,
          maxMatches: 3,
        },
      ),
    ).toThrow(/usable timestamped transcript/i);
    expect(() =>
      shapeYoutubeTranscriptSearchOutput(
        [
          {
            video_id: "video123456",
            status: "success",
            transcript: [{ start: 0, text: "missing end" }],
          },
        ],
        {
          videoUrl: "https://www.youtube.com/watch?v=video123456",
          query: "workos",
          contextSeconds: 60,
          maxMatches: 3,
        },
      ),
    ).toThrow(/usable timestamped transcript/i);
    expect(() =>
      shapeYoutubeTranscriptSearchOutput(
        [
          {
            video_id: "different12",
            status: "success",
            transcript: [{ start: 0, end: 1, text: "WorkOS" }],
          },
        ],
        {
          videoUrl: "https://www.youtube.com/watch?v=video123456",
          query: "workos",
          contextSeconds: 60,
          maxMatches: 3,
        },
      ),
    ).toThrow(/usable timestamped transcript/i);
  });
});
