// Generated by scripts/package-official-plugins.ts. Do not edit by hand.

import artifact1 from "./attio.json";
import artifact2 from "./betterstack.json";
import artifact0 from "./convex.json";
import artifact3 from "./fathom.json";
import artifact4 from "./github.json";
import artifact5 from "./gmail.json";
import artifact7 from "./google-admin.json";
import artifact8 from "./google-calendar.json";
import artifact9 from "./google-drive.json";
import artifact6 from "./granola.json";
import artifact10 from "./hubspot.json";
import artifact11 from "./infisical.json";
import artifact12 from "./jamie.json";
import artifact13 from "./latitude.json";
import artifact14 from "./linear.json";
import artifact15 from "./neon.json";
import artifact16 from "./notion.json";
import artifact17 from "./posthog.json";
import artifact19 from "./render.json";
import artifact18 from "./resend.json";
import artifact21 from "./signoz.json";
import artifact22 from "./slack.json";
import artifact24 from "./stripe.json";
import artifact23 from "./supabase.json";
import artifact20 from "./vercel.json";
import artifact25 from "./x.json";
import artifact26 from "./yc-advise.json";

export const OFFICIAL_PLUGIN_ARTIFACTS = {
  convex: artifact0,
  attio: artifact1,
  betterstack: artifact2,
  fathom: artifact3,
  github: artifact4,
  gmail: artifact5,
  granola: artifact6,
  "google-admin": artifact7,
  "google-calendar": artifact8,
  "google-drive": artifact9,
  hubspot: artifact10,
  infisical: artifact11,
  jamie: artifact12,
  latitude: artifact13,
  linear: artifact14,
  neon: artifact15,
  notion: artifact16,
  posthog: artifact17,
  resend: artifact18,
  render: artifact19,
  vercel: artifact20,
  signoz: artifact21,
  slack: artifact22,
  supabase: artifact23,
  stripe: artifact24,
  x: artifact25,
  "yc-advise": artifact26,
};
