// Generated by scripts/package-official-plugins.ts. Do not edit by hand.

import artifact1 from "./attio.json";
import artifact2 from "./betterstack.json";
import artifact0 from "./convex.json";
import artifact3 from "./fathom.json";
import artifact4 from "./github.json";
import artifact5 from "./gmail.json";
import artifact7 from "./google-calendar.json";
import artifact8 from "./google-drive.json";
import artifact6 from "./granola.json";
import artifact9 from "./hubspot.json";
import artifact10 from "./infisical.json";
import artifact11 from "./jamie.json";
import artifact12 from "./latitude.json";
import artifact13 from "./linear.json";
import artifact14 from "./neon.json";
import artifact15 from "./notion.json";
import artifact26 from "./outlook.json";
import artifact27 from "./outlook-calendar.json";
import artifact16 from "./posthog.json";
import artifact18 from "./render.json";
import artifact17 from "./resend.json";
import artifact20 from "./signoz.json";
import artifact21 from "./slack.json";
import artifact23 from "./stripe.json";
import artifact22 from "./supabase.json";
import artifact19 from "./vercel.json";
import artifact24 from "./x.json";
import artifact25 from "./yc-advise.json";

export const OFFICIAL_PLUGIN_ARTIFACTS = {
  convex: artifact0,
  attio: artifact1,
  betterstack: artifact2,
  fathom: artifact3,
  github: artifact4,
  gmail: artifact5,
  granola: artifact6,
  "google-calendar": artifact7,
  "google-drive": artifact8,
  hubspot: artifact9,
  infisical: artifact10,
  jamie: artifact11,
  latitude: artifact12,
  linear: artifact13,
  neon: artifact14,
  notion: artifact15,
  posthog: artifact16,
  resend: artifact17,
  render: artifact18,
  vercel: artifact19,
  signoz: artifact20,
  slack: artifact21,
  supabase: artifact22,
  stripe: artifact23,
  x: artifact24,
  "yc-advise": artifact25,
  outlook: artifact26,
  "outlook-calendar": artifact27,
};
