// Generated by scripts/package-official-plugins.ts. Do not edit by hand.

import artifact3 from "./attio.json";
import artifact4 from "./betterstack.json";
import artifact2 from "./convex.json";
import artifact5 from "./fathom.json";
import artifact6 from "./github.json";
import artifact7 from "./gmail.json";
import artifact9 from "./google-calendar.json";
import artifact10 from "./google-drive.json";
import artifact8 from "./granola.json";
import artifact11 from "./hubspot.json";
import artifact12 from "./infisical.json";
import artifact13 from "./jamie.json";
import artifact14 from "./latitude.json";
import artifact15 from "./linear.json";
import artifact16 from "./neon.json";
import artifact17 from "./notion.json";
import artifact0 from "./outlook.json";
import artifact1 from "./outlook-calendar.json";
import artifact18 from "./posthog.json";
import artifact20 from "./render.json";
import artifact19 from "./resend.json";
import artifact22 from "./signoz.json";
import artifact23 from "./slack.json";
import artifact25 from "./stripe.json";
import artifact24 from "./supabase.json";
import artifact21 from "./vercel.json";
import artifact26 from "./x.json";
import artifact27 from "./yc-advise.json";

export const OFFICIAL_PLUGIN_ARTIFACTS = {
  outlook: artifact0,
  "outlook-calendar": artifact1,
  convex: artifact2,
  attio: artifact3,
  betterstack: artifact4,
  fathom: artifact5,
  github: artifact6,
  gmail: artifact7,
  granola: artifact8,
  "google-calendar": artifact9,
  "google-drive": artifact10,
  hubspot: artifact11,
  infisical: artifact12,
  jamie: artifact13,
  latitude: artifact14,
  linear: artifact15,
  neon: artifact16,
  notion: artifact17,
  posthog: artifact18,
  resend: artifact19,
  render: artifact20,
  vercel: artifact21,
  signoz: artifact22,
  slack: artifact23,
  supabase: artifact24,
  stripe: artifact25,
  x: artifact26,
  "yc-advise": artifact27,
};
