export const DEFAULT_WORKFLOW_SCHEDULE_CRON = "0 9 * * 1-5";
export {
  DEFAULT_WORKFLOW_EVENT_PROMPT,
  DEFAULT_WORKFLOW_SCHEDULE_PROMPT,
} from "@opencompany/core/workflows";
export const DEFAULT_WORKFLOW_SCHEDULE_TIMEZONE = "UTC";
