import { GoatActionExecutionError } from "@/lib/actions/types";
import { MAX_CAPABILITY_PAYLOAD_STRING_CHARS } from "@/lib/capabilities/sanitize";

const MAX_PROVIDER_SEGMENTS = 20_000;
const MAX_PROVIDER_SEGMENT_CHARS = 3_000;
const MAX_EXCERPT_CHARS = 3_600;
const MAX_METADATA_CHARS = 500;
const MAX_AVAILABLE_LANGUAGES = 20;

type TranscriptSegment = {
  start: number;
  end: number;
  text: string;
};

type ParsedYoutubeTranscript = {
  video: {
    id: string;
    url: string;
    title?: string;
    channel?: string;
    language?: string;
    selectedLanguage?: string;
    isAutoGenerated?: boolean;
    durationSeconds?: number;
  };
  availableLanguages?: string[];
  segments: TranscriptSegment[];
};

type TranscriptMatchWindow = {
  start: number;
  end: number;
  hitIndexes: number[];
};

export function shapeYoutubeTranscriptOutput(output: unknown, videoUrl: string) {
  const parsed = parseYoutubeTranscriptProviderOutput(output, videoUrl);
  const transcript = parsed.segments.map((segment) => segment.text).join(" ");
  const result = {
    video: parsed.video,
    segmentCount: parsed.segments.length,
    ...(parsed.availableLanguages === undefined
      ? {}
      : { availableLanguages: parsed.availableLanguages }),
    transcript,
  };
  if (JSON.stringify(result).length > MAX_CAPABILITY_PAYLOAD_STRING_CHARS) {
    throw new GoatActionExecutionError(
      "provider_error",
      "This video's complete transcript is too large to return safely in one action result.",
    );
  }
  return result;
}

export function shapeYoutubeTranscriptSearchOutput(
  output: unknown,
  input: {
    videoUrl: string;
    query: string;
    contextSeconds: number;
    maxMatches: number;
  },
) {
  const parsed = parseYoutubeTranscriptProviderOutput(output, input.videoUrl);
  const segments = parsed.segments;
  const normalizedQuery = normalizeSearchText(input.query);
  const hitIndexes = findMatchingSegmentIndexes(segments, normalizedQuery);
  const windows = transcriptMatchWindows(
    segments,
    hitIndexes,
    input.contextSeconds,
    input.maxMatches,
  );
  const videoUrl = input.videoUrl;

  return {
    video: parsed.video,
    query: input.query,
    searchedSegmentCount: segments.length,
    matchedSegmentCount: hitIndexes.length,
    ...(parsed.availableLanguages === undefined
      ? {}
      : { availableLanguages: parsed.availableLanguages }),
    matches: windows.map((window) => {
      const excerptSegments = segments.filter(
        (segment) => segment.end >= window.start && segment.start <= window.end,
      );
      const startSeconds = excerptSegments[0]?.start ?? window.start;
      const endSeconds = excerptSegments.at(-1)?.end ?? window.end;
      return {
        startSeconds,
        endSeconds,
        startTime: formatTimestamp(startSeconds),
        endTime: formatTimestamp(endSeconds),
        url: timestampedYoutubeUrl(videoUrl, startSeconds),
        text: boundedExcerptText(excerptSegments, segments[window.hitIndexes[0]!]!),
      };
    }),
    ...(windows.length === 0
      ? {
          note: "No transcript excerpt matched the requested phrase. Try one shorter spelling variant if the wording may differ.",
        }
      : {}),
  };
}

function parseYoutubeTranscriptProviderOutput(
  output: unknown,
  videoUrl: string,
): ParsedYoutubeTranscript {
  const item = providerResultItem(output);
  if (readString(item.status, 50)?.toLowerCase() === "error") {
    throw transcriptProviderError();
  }
  const requestedVideoId = youtubeVideoId(videoUrl);
  if (readString(item.video_id, 100) !== requestedVideoId) {
    throw transcriptProviderError();
  }
  const title = readString(item.title, MAX_METADATA_CHARS);
  const channel = readString(item.channel_name, MAX_METADATA_CHARS);
  const language = readString(item.language, 100);
  const selectedLanguage = readString(item.selected_language, 100);
  const durationSeconds = readNonNegativeNumber(item.duration_seconds);
  const availableLanguages = readStringArray(item.available_languages, MAX_AVAILABLE_LANGUAGES);
  return {
    video: {
      id: requestedVideoId,
      url: videoUrl,
      ...(title === undefined ? {} : { title }),
      ...(channel === undefined ? {} : { channel }),
      ...(language === undefined ? {} : { language }),
      ...(selectedLanguage === undefined ? {} : { selectedLanguage }),
      ...(typeof item.is_auto_generated === "boolean"
        ? { isAutoGenerated: item.is_auto_generated }
        : {}),
      ...(durationSeconds === undefined ? {} : { durationSeconds }),
    },
    ...(availableLanguages === undefined ? {} : { availableLanguages }),
    segments: transcriptSegments(item.transcript),
  };
}

function providerResultItem(output: unknown): Record<string, unknown> {
  const candidates = Array.isArray(output)
    ? output
    : isRecord(output) && Array.isArray(output.items)
      ? output.items
      : [output];
  if (candidates.length !== 1 || !isRecord(candidates[0])) throw transcriptProviderError();
  const item = candidates[0];
  return item;
}

function transcriptSegments(value: unknown): TranscriptSegment[] {
  if (!Array.isArray(value) || value.length === 0 || value.length > MAX_PROVIDER_SEGMENTS) {
    throw transcriptProviderError();
  }
  const segments = value.map((entry) => {
    if (!isRecord(entry)) throw transcriptProviderError();
    const start = readNonNegativeNumber(entry.start);
    const end = readNonNegativeNumber(entry.end);
    const text = readString(entry.text, MAX_PROVIDER_SEGMENT_CHARS);
    if (start === undefined || end === undefined || end < start || !text) {
      throw transcriptProviderError();
    }
    return { start, end, text };
  });
  return segments.sort((left, right) => left.start - right.start);
}

function findMatchingSegmentIndexes(segments: TranscriptSegment[], query: string) {
  const indexes = new Set<number>();
  for (let index = 0; index < segments.length; index += 1) {
    const current = normalizeSearchText(segments[index]!.text);
    if (current.includes(query)) {
      indexes.add(index);
      continue;
    }
    const next = segments[index + 1];
    const normalizedNext = next ? normalizeSearchText(next.text) : "";
    if (
      next &&
      !normalizedNext.includes(query) &&
      normalizeSearchText(`${segments[index]!.text} ${next.text}`).includes(query)
    ) {
      indexes.add(index);
    }
  }
  return [...indexes];
}

function transcriptMatchWindows(
  segments: TranscriptSegment[],
  hitIndexes: number[],
  contextSeconds: number,
  maxMatches: number,
) {
  const windows: TranscriptMatchWindow[] = [];
  for (const hitIndex of hitIndexes) {
    const hit = segments[hitIndex]!;
    const start = Math.max(0, hit.start - contextSeconds);
    const end = hit.end + contextSeconds;
    const previous = windows.at(-1);
    if (previous && start <= previous.end) {
      previous.end = Math.max(previous.end, end);
      previous.hitIndexes.push(hitIndex);
      continue;
    }
    if (windows.length >= maxMatches) break;
    windows.push({ start, end, hitIndexes: [hitIndex] });
  }
  return windows;
}

function boundedExcerptText(segments: TranscriptSegment[], anchor: TranscriptSegment): string {
  const text = segments.map((segment) => segment.text).join(" ");
  if (text.length <= MAX_EXCERPT_CHARS) return text;

  const anchorOffset = Math.max(0, text.indexOf(anchor.text));
  const coreLimit = MAX_EXCERPT_CHARS - 2;
  const surroundingChars = Math.max(0, coreLimit - anchor.text.length);
  const start = Math.max(0, anchorOffset - Math.floor(surroundingChars / 2));
  const end = Math.min(text.length, start + coreLimit);
  const adjustedStart = Math.max(0, end - coreLimit);
  return `${adjustedStart > 0 ? "…" : ""}${text.slice(adjustedStart, end)}${
    end < text.length ? "…" : ""
  }`;
}

function timestampedYoutubeUrl(videoUrl: string, startSeconds: number) {
  try {
    const url = new URL(videoUrl);
    url.searchParams.set("t", `${Math.max(0, Math.floor(startSeconds))}s`);
    return url.toString();
  } catch {
    return videoUrl;
  }
}

function youtubeVideoId(videoUrl: string) {
  try {
    const id = new URL(videoUrl).searchParams.get("v")?.trim();
    if (id && /^[A-Za-z0-9_-]{11}$/.test(id)) return id;
  } catch {
    // The reviewed action adapter supplies a canonical URL. Invalid input here
    // means the provider result cannot be safely associated with that request.
  }
  throw transcriptProviderError();
}

function formatTimestamp(seconds: number) {
  const rounded = Math.max(0, Math.floor(seconds));
  const hours = Math.floor(rounded / 3_600);
  const minutes = Math.floor((rounded % 3_600) / 60);
  const remainingSeconds = rounded % 60;
  return [hours, minutes, remainingSeconds]
    .map((value) => value.toString().padStart(2, "0"))
    .join(":");
}

function normalizeSearchText(value: string) {
  return value
    .normalize("NFKC")
    .toLocaleLowerCase("en-US")
    .replace(/[^\p{L}\p{N}]+/gu, " ")
    .trim()
    .replace(/\s+/g, " ");
}

function readString(value: unknown, maxLength: number) {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim();
  if (!trimmed || trimmed.length > maxLength) return undefined;
  return trimmed;
}

function readStringArray(value: unknown, maxItems: number) {
  if (!Array.isArray(value)) return undefined;
  const items = value
    .slice(0, maxItems)
    .map((entry) => readString(entry, 100))
    .filter((entry): entry is string => Boolean(entry));
  return items.length > 0 ? items : undefined;
}

function readNonNegativeNumber(value: unknown) {
  return typeof value === "number" && Number.isFinite(value) && value >= 0 ? value : undefined;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function transcriptProviderError() {
  return new GoatActionExecutionError(
    "provider_error",
    "The transcript provider did not return a usable timestamped transcript.",
  );
}
