import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { OFFICIAL_PLUGIN_SOURCES } from "../packages/agent-runtime/src/official-plugin-catalog";
import {
  createGitHubPluginFetcher,
  resolvePlugin,
} from "../packages/agent-runtime/src/plugin-resolver";
import { parseSkillUrl, type SkillTree } from "../packages/agent-runtime/src/skill-resolver";

const execFileAsync = promisify(execFile);
async function githubJson<T>(endpoint: string, jq: string): Promise<T> {
  // Maintainer authentication is confined to this explicit packaging command. The runtime never
  // receives these credentials, and release builds consume only the checked-in artifacts.
  const { stdout } = await execFileAsync("gh", ["api", endpoint, "--jq", jq], {
    maxBuffer: 16 * 1024 * 1024,
  });
  return JSON.parse(stdout) as T;
}
const fetcher = {
  ...createGitHubPluginFetcher(),
  async resolveCommit(owner: string, repo: string, ref: string) {
    return githubJson<string>(`repos/${owner}/${repo}/commits/${ref}`, ".sha | tojson");
  },
  async fetchTree(owner: string, repo: string, commit: string) {
    return githubJson<SkillTree>(
      `repos/${owner}/${repo}/git/trees/${commit}?recursive=1`,
      "{entries: [.tree[] | {path, type, mode} + (if .size != null then {size} else {} end)], truncated}",
    );
  },
};

// Run explicitly when reviewing catalog updates, never during builds or installation.
const directory = new URL(
  "../packages/agent-runtime/src/official-plugin-artifacts/",
  import.meta.url,
);
await mkdir(directory, { recursive: true });
const artifacts = [];
for (const [name, source] of Object.entries(OFFICIAL_PLUGIN_SOURCES)) {
  const parsed = parseSkillUrl(source);
  if (
    parsed.owner !== "useopencompany" ||
    parsed.repo !== "plugins" ||
    !/^[0-9a-f]{40}$/u.test(parsed.ref ?? "") ||
    parsed.subpath !== name
  ) {
    throw new Error(
      `Official plugin ${name} must pin its public package directory to a full commit.`,
    );
  }
  const plugin = await resolvePlugin({
    url: source,
    fetcher,
    trustedCapabilitySources: ["useopencompany/plugins"],
  });
  if (plugin.resolvedCommit !== parsed.ref || plugin.manifest.name !== name) {
    throw new Error(`Official plugin ${name} does not match its catalog pin.`);
  }
  if (
    plugin.report.skills.some((skill) => skill.status !== "valid") ||
    (plugin.report.mcp.status !== "absent" &&
      (plugin.report.mcp.status !== "parsed" ||
        plugin.report.mcp.reports.some((server) => server.status === "invalid"))) ||
    (plugin.report.capabilities.status !== "absent" &&
      (plugin.report.capabilities.status !== "parsed" ||
        plugin.report.capabilities.issues.length > 0)) ||
    (plugin.report.events.status !== "absent" &&
      (plugin.report.events.status !== "parsed" || plugin.report.events.issues.length > 0))
  ) {
    throw new Error(
      `Official plugin ${name} has validation issues: ${JSON.stringify(plugin.report)}`,
    );
  }
  const artifact = {
    source,
    resolvedCommit: plugin.resolvedCommit,
    integrity: plugin.integrity,
    files: plugin.files.map((file) => ({
      path: file.path,
      executable: file.executable,
      contentBase64: Buffer.from(file.content).toString("base64"),
    })),
  };
  artifacts.push({ name, artifact });
}
// Resolve and validate the entire catalog before writing any release artifacts.
for (const { name, artifact } of artifacts) {
  await writeFile(new URL(`${name}.json`, directory), `${JSON.stringify(artifact, null, 2)}\n`);
}
await writeFile(
  new URL("index.ts", directory),
  [
    "// Generated by scripts/package-official-plugins.ts. Do not edit by hand.",
    ...artifacts.map(({ name }, index) => `import artifact${index} from "./${name}.json";`),
    "",
    "export const OFFICIAL_PLUGIN_ARTIFACTS = {",
    ...artifacts.map(({ name }, index) => `  "${name}": artifact${index},`),
    "};",
    "",
  ].join("\n"),
);
await execFileAsync(fileURLToPath(new URL("../node_modules/.bin/biome", import.meta.url)), [
  "check",
  "--write",
  fileURLToPath(directory),
]);
console.log(`Packaged ${artifacts.length} validated official plugins.`);
